---
id: droonga-meetup-1
base_name: droonga-world
tags:
- rabbit
- groonga
- droonga
presentation_date: 2014-07-30
version: 2014.7.30.1
licenses:
- CC BY-SA 3.0
slideshare_id: droonga-meetup-1
speaker_deck_id: droongayi-xing-hou-falseshi-jie
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
